apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Scheduler.Name }}
  namespace: kube-system
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: {{ .Scheduler.Name }}
    leaderElection:
      leaderElect: false
    clientConnection:
      qps: 8000
      burst: 16000
